## =============================================================================
## pynq_z2.xdc — PYNQ-Z2 Master Constraints
## Project   : 2D GPU Accelerator
## Target    : xc7z020clg400-1 (PYNQ-Z2)
##
## Includes:
##   - System clocks (125 MHz PS FCLK → PL fabric clock)
##   - HDMI TX output pins (via Digilent HDMI IP)
##   - Timing constraints for AXI fabric (100 MHz) and pixel clock (148.5 MHz)
##   - False path declarations for cross-clock-domain signals
## =============================================================================

## -----------------------------------------------------------------------------
## System Clock: PS FCLK_CLK0 → fabric clock (100 MHz)
## The Zynq PS drives this via the FCLK_CLK0 port in the block design.
## This constraint applies to the external 125 MHz oscillator that feeds the PS.
## -----------------------------------------------------------------------------
set_property -dict { PACKAGE_PIN H16  IOSTANDARD LVCMOS33 } [get_ports { sysclk }]
create_clock -name sysclk -period 8.000 [get_ports { sysclk }]

## The AXI fabric clock is generated internally from the PS.
## Declare it for timing analysis:
create_clock -name clk_100mhz -period 10.000 \
    [get_pins { design_1_i/processing_system7_0/inst/PS7_i/FCLKCLK[0] }]

## -----------------------------------------------------------------------------
## HDMI TX — Digilent HDMI TX IP uses these pins on PYNQ-Z2
## Pixel clock: up to 148.5 MHz (1080p60) / 74.25 MHz (720p60)
## Note: Actual pixel clock is generated by the HDMI IP's MMCM from FCLK_CLK1
## -----------------------------------------------------------------------------

## HDMI TX Clock
set_property -dict { PACKAGE_PIN L16  IOSTANDARD TMDS_33 } [get_ports { hdmi_tx_clk_p }]
set_property -dict { PACKAGE_PIN L17  IOSTANDARD TMDS_33 } [get_ports { hdmi_tx_clk_n }]

## HDMI TX Data Channels
set_property -dict { PACKAGE_PIN K17  IOSTANDARD TMDS_33 } [get_ports { hdmi_tx_d_p[0] }]
set_property -dict { PACKAGE_PIN K18  IOSTANDARD TMDS_33 } [get_ports { hdmi_tx_d_n[0] }]
set_property -dict { PACKAGE_PIN K19  IOSTANDARD TMDS_33 } [get_ports { hdmi_tx_d_p[1] }]
set_property -dict { PACKAGE_PIN J19  IOSTANDARD TMDS_33 } [get_ports { hdmi_tx_d_n[1] }]
set_property -dict { PACKAGE_PIN H17  IOSTANDARD TMDS_33 } [get_ports { hdmi_tx_d_p[2] }]
set_property -dict { PACKAGE_PIN H18  IOSTANDARD TMDS_33 } [get_ports { hdmi_tx_d_n[2] }]

## HDMI TX Hot-Plug Detect
set_property -dict { PACKAGE_PIN F17  IOSTANDARD LVCMOS33 } [get_ports { hdmi_tx_hpd }]

## HDMI TX CEC (optional, leave unconnected if not used)
set_property -dict { PACKAGE_PIN G17  IOSTANDARD LVCMOS33 } [get_ports { hdmi_tx_cec }]

## HDMI TX I2C (DDC — display data channel)
set_property -dict { PACKAGE_PIN G18  IOSTANDARD LVCMOS33 } [get_ports { hdmi_tx_scl }]
set_property -dict { PACKAGE_PIN F18  IOSTANDARD LVCMOS33 } [get_ports { hdmi_tx_sda }]

## -----------------------------------------------------------------------------
## Pixel Clock (generated by HDMI IP MMCM inside PL — 74.25 MHz for 720p60)
## Declared here for timing closure; actual source is the MMCM output.
## -----------------------------------------------------------------------------
create_clock -name pixel_clk -period 13.468 \
    [get_pins { design_1_i/rgb2dvi_0/U0/ClockGenInternal.ClockGenInternal_i/Mmcm/CLKOUT0 }]

## -----------------------------------------------------------------------------
## Timing Exceptions
## -----------------------------------------------------------------------------

## False path from PS reset (slow, asynchronous)
set_false_path -from [get_ports { rst_n }]

## False path between AXI fabric clock and pixel clock domains
## (frame pointer is transferred via handshake, not direct CDC flop)
set_false_path -from [get_clocks { clk_100mhz }] -to [get_clocks { pixel_clk }]
set_false_path -from [get_clocks { pixel_clk }]  -to [get_clocks { clk_100mhz }]

## -----------------------------------------------------------------------------
## I/O timing (AXI GP/HP ports are internal PS — no I/O constraints needed)
## -----------------------------------------------------------------------------

## Keep hierarchy for easier timing analysis in Vivado
set_property KEEP_HIERARCHY TRUE [get_cells { design_1_i/drawing_engine_0 }]
